version: '3'
services:
  chess-api:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 9001:9001
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: s7aSm5xEjF7E37ABp3he
      MONGODB_URL: mongodb://root:s7aSm5xEjF7E37ABp3he@mongo:27017/
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s7aSm5xEjF7E37ABp3he
